CREATE TABLE comentarios(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  texto TEXT NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tarefa_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  ativo BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (tarefa_id) REFERENCES tarefas(id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);